resources:
  - name: buildami_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/buildami
      branch: master

  - name: ami_reqKick_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqKick
      branch: master

  - name: ami_bits_access_cli
    type: cliConfig
    integration: aws_bits_access
    pointer:
      region: us-east-1

  - name: ami_bits_access
    type: integration
    integration: aws_bits_access

  - name: ami_prod_access
    type: integration
    integration: aws_prod_access

  - name: ship_bits_gcp
    type: cliConfig
    integration: ship_bits_gcp_svc
    versionTemplate:
      region: "us-west1-a"

  - name: admiralami_params
    type: params
    version:
      params:
        SOURCE_AMI: "ami-772aa961"
        VPC_ID: "vpc-2d9a894f"
        SUBNET_ID: "subnet-42bfef04"
        SECURITY_GROUP_ID: "sg-9df159f8"
        REGION: "us-east-1"

jobs:
  - name: trig_gcp_img_prep
    type: runSh
    steps:
      - TASK:
          script:
            - ls -al

######################### Admiral Image ##################################
  - name: baseadmiralami_prep
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: buildami_repo
        switch: off
      - IN: ami_bits_access
        switch: off
      - IN: ami_prod_access
        switch: off
      - IN: admiralami_params
        switch: off
      - TASK:
          script:
            - pushd $(shipctl get_resource_state "buildami_repo")
            - cd admiral
            - ./admiralPack.sh baseadmiralami_prep ami_bits_access ami_prod_access
            - popd
    on_failure:
      - script: echo 'failed'
      - NOTIFY: rc_slack
