resources:
  - name: distrobase_dd_repo
    type: gitRepo
    integration: avinci_gh
    versionTemplate:
      sourceName: "dry-dock/distrobase"
      branch: master

  - name: distrobase_dd_img
    type: image
    integration: shipDH
    versionTemplate:
      sourceName: "drydock/distrobase"
      versionName: master

jobs:
  - name: distrobase_x8664_build
    type: runSh
    steps:
      - IN: distrobase_dd_repo
      - TASK:
          name: distrobase_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - IMG_OUT: "distrobase_dd_img"
                - RES_REPO: "distrobase_dd_repo"
          script:
            - $script:REPO_COMMIT=$(shipctl get_resource_version_key "$env:RES_REPO" "shaData.commitSha")
            - $script:IMG_NAME=$(shipctl get_resource_version_key "$env:IMG_OUT" "sourceName")
            - $script:DH_USR_NAME=$(shipctl get_integration_resource_field "$env:IMG_OUT" "userName")
            - $script:DH_PASS=$(shipctl get_integration_resource_field "$env:IMG_OUT" "password")
            - pushd $(shipctl get_resource_state "$env:RES_REPO")
            - ./build.sh
            - docker login -u "$DH_USR_NAME" -p "$DH_PASS"
            - docker push "${IMG_NAME}:${env:REL_VER}"
      - OUT: distrobase_dd_img
    on_success:
      script:
        - shipctl put_resource_state_multi "$env:JOB_NAME" "versionName=${env:REL_VER}" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT"
        - shipctl put_resource_state_multi "$env:IMG_OUT" "versionName=${env:REL_VER}" "IMG_REPO_COMMIT_SHA=$REPO_COMMIT" "BUILD_NUMBER=${env:BUILD_NUMBER}"
