resources:
  - name: u16microbase_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    versionTemplate:
      sourceName: "dry-dock/aarch64_u16microbase"
      branch: master

  - name: u16microbase_aarch64_dd_img
    type: image
    integration: shipDH
    versionTemplate:
      sourceName: "drydock/aarch64_u16microbase"
      versionName: master

  - name: u16_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch64_u16"
      branch: master

  - name: u16_aarch64_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch64_u16"
    seed:
      versionName: master

  - name: u16all_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch64_u16all"
      branch: master

  - name: u16all_aarch64_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch64_u16all"
    seed:
      versionName: master

  - name: u16nodall_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch64_u16nodall"
      branch: master

  - name: u16nodall_aarch64_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch64_u16nodall"
    seed:
      versionName: master

  - name: u16pytall_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch64_u16pytall"
      branch: master

  - name: u16pytall_aarch64_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch64_u16pytall"
    seed:
      versionName: master

  - name: u16javall_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch64_u16javall"
      branch: master

  - name: u16javall_aarch64_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch64_u16javall"
    seed:
      versionName: master

  - name: u16cppall_aarch64_dd_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: "dry-dock/aarch64_u16cppall"
      branch: master

  - name: u16cppall_aarch64_dd_img
    type: image
    integration: shipDH
    pointer:
      sourceName: "drydock/aarch64_u16cppall"
    seed:
      versionName: master

jobs:
  - name: u16microbase_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16microbase_aarch64_dd_repo
      - IN: u16_aarch64_dd_img
      - TASK:
          name: u16microbase_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16microbase_aarch64_dd_repo"
                - IMG_OUT: "u16microbase_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16microbase_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

  - name: u16microbase_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16microbase_aarch64_dd_repo
        switch: off
      - IN: u16microbase_aarch64_dd_img
        switch: off
      - TASK:
          name: u16microbase_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16microbase_aarch64_dd_img"
                - RES_REPO: "u16microbase_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success

  - name: u16_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16_aarch64_dd_repo
      - TASK:
          name: u16_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16_aarch64_dd_repo"
                - IMG_OUT: "u16_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

  - name: u16all_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16all_aarch64_dd_repo
      - IN: u16_aarch64_dd_img
      - TASK:
          name: u16all_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16all_aarch64_dd_repo"
                - IMG_OUT: "u16all_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16all_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

  - name: u16nodall_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16nodall_aarch64_dd_repo
      - IN: u16all_aarch64_dd_img
      - TASK:
          name: u16nodall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16nodall_aarch64_dd_repo"
                - IMG_OUT: "u16nodall_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16nodall_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

  - name: u16pytall_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16pytall_aarch64_dd_repo
      - IN: u16all_aarch64_dd_img
      - TASK:
          name: u16pytall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16pytall_aarch64_dd_repo"
                - IMG_OUT: "u16pytall_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16pytall_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

  - name: u16javall_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16javall_aarch64_dd_repo
      - IN: u16all_aarch64_dd_img
      - TASK:
          name: u16pytall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16javall_aarch64_dd_repo"
                - IMG_OUT: "u16javall_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16javall_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

  - name: u16cppall_aarch64_build
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: aarch64_u1604_cus_01
      container: false
    steps:
      - IN: u16cppall_aarch64_dd_repo
      - IN: u16all_aarch64_dd_img
      - TASK:
          name: u16cppall_build
          runtime:
            options:
              env:
                - REL_VER: "master"
                - RES_REPO: "u16cppall_aarch64_dd_repo"
                - IMG_OUT: "u16cppall_aarch64_dd_img"
          script:
            - *build_ship_assets
      - OUT: u16cppall_aarch64_dd_img
    on_success:
      script:
        - *build_ship_assets_on_success

#####
  - name: u16_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16_aarch64_dd_repo
        switch: off
      - IN: u16_aarch64_dd_img
        switch: off
      - TASK:
          name: u16_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16_aarch64_dd_img"
                - RES_REPO: "u16_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success

  - name: u16all_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16all_aarch64_dd_repo
        switch: off
      - IN: u16all_aarch64_dd_img
        switch: off
      - TASK:
          name: u16all_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16all_aarch64_dd_img"
                - RES_REPO: "u16all_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success

  - name: u16nodall_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16nodall_aarch64_dd_repo
        switch: off
      - IN: u16nodall_aarch64_dd_img
        switch: off
      - TASK:
          name: u16nodall_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16nodall_aarch64_dd_img"
                - RES_REPO: "u16nodall_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success

  - name: u16pytall_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16pytall_aarch64_dd_repo
        switch: off
      - IN: u16pytall_aarch64_dd_img
        switch: off
      - TASK:
          name: u16pytall_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16pytall_aarch64_dd_img"
                - RES_REPO: "u16pytall_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success

  - name: u16cppall_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16cppall_aarch64_dd_repo
        switch: off
      - IN: u16cppall_aarch64_dd_img
        switch: off
      - TASK:
          name: u16cppall_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16cppall_aarch64_dd_img"
                - RES_REPO: "u16cppall_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success

  - name: u16javall_aarch64_tag
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    integrations:
      - ship_ssh
    steps:
      - IN: drydock_release
      - IN: u16javall_aarch64_dd_repo
        switch: off
      - IN: u16javall_aarch64_dd_img
        switch: off
      - TASK:
          name: u16javall_tag
          runtime:
            options:
              env:
                - RES_VER: "drydock_release"
                - RES_IMG: "u16javall_aarch64_dd_img"
                - RES_REPO: "u16javall_aarch64_dd_repo"
          script:
            - *tag_ship_assets
    on_success:
      script:
        - *tag_ship_assets_on_success
